name: Linux

on:
  push:
    branches: [ main, dev, ld ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install dependency
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get -y install libzstd-dev
    - name: make
      run: make -j4
    - name: download and test example data
      run: |
        make data
        make example_tests
    - name: test LD module
      run: |
        make hwe
        make ld_matrix
        make ld_r2
        make ld_clump
        make ld_tests

  build-aarch64:
    name: Build on Linux (aarch64)
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Run aarch64 build and tests
      uses: uraimo/run-on-arch-action@v3
      with:
        arch: aarch64
        distro: ubuntu22.04
        run: |
          apt-get update
          apt-get -y install libzstd-dev build-essential
          make -j4
          make data
          make example_tests
          make hwe
          make ld_matrix
          make ld_r2
          make ld_clump
          make ld_tests
