name: Linux build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependency
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get -y install zstd

    - name: make
      run: make

    - name: run test
      run: sh misc/test.sh
