name: Linux

on:
  push:
    branches: [ main, dev, ld ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install dependency
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential libzstd-dev zlib1g-dev wget
    - name: Build and run full test suite
      run: |
        make -j4
        make test_full

  build-aarch64:
    name: Build on Linux (aarch64)
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Run aarch64 build and tests
      uses: uraimo/run-on-arch-action@v3
      with:
        arch: aarch64
        distro: ubuntu22.04
        run: |
          apt-get update
          apt-get -y install build-essential libzstd-dev zlib1g-dev wget
          make -j4
          make test_aarch64
