name: Linux

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependency
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get -y install libzstd-dev

    - name: make
      run: make -j4

    - name: test
      run: ./PCAone --help
