name: MacOS build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: install gnu gcc
      run: brew install gcc

    - name: make
      run: |
        export CC=$(find $(brew --prefix)/bin/ -name "gcc-[0-9]*" | tail -1)
        export CXX=$(find $(brew --prefix)/bin/ -name "g++-[0-9]*" | tail -1)
        make
