name: MacOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependency
      run: brew install llvm

    - name: make
      run: |
        export CC=$(brew --prefix llvm)/bin/clang
        export CXX=$(brew --prefix llvm)/bin/clang++
        export LDFLAGS="-L"$(brew --prefix llvm)/lib
        export CPPFLAGS="-I"$(brew --prefix llvm)/include
        make -j4 AVX=0 INC_PATH=$(brew --prefix llvm)/include LIB_PATH=$(brew --prefix llvm)/lib

    - name: test
      run: ./PCAone --help
