name: MacOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependency
      run: brew install libomp

    - name: make
      run: make -j4

    - name: test
      run: ./PCAone --help
